export const CLUB_TYPE_OPTIONS = [
  { label: "Driver", value: "DRIVER" },
  { label: "3 Wood", value: "FW3" },
  { label: "4 Wood", value: "FW4" },
  { label: "5 Wood", value: "FW5" },
  { label: "7 Wood", value: "FW7" },
  { label: "9 Wood", value: "FW9" },
  { label: "2 Hybrid", value: "HY2" },
  { label: "3 Hybrid", value: "HY3" },
  { label: "4 Hybrid", value: "HY4" },
  { label: "5 Hybrid", value: "HY5" },
  { label: "6 Hybrid", value: "HY6" },
  { label: "7 Hybrid", value: "HY7" },
  { label: "1 Iron", value: "IRON1" },
  { label: "2 Iron", value: "IRON2" },
  { label: "3 Iron", value: "IRON3" },
  { label: "4 Iron", value: "IRON4" },
  { label: "5 Iron", value: "IRON5" },
  { label: "6 Iron", value: "IRON6" },
  { label: "7 Iron", value: "IRON7" },
  { label: "8 Iron", value: "IRON8" },
  { label: "9 Iron", value: "IRON9" },
  { label: "PW", value: "WEDGE_PW" },
  { label: "AW", value: "WEDGE_AW" },
  { label: "SW", value: "WEDGE_SW" },
  { label: "LW", value: "WEDGE_LW" },
  { label: "Putter", value: "PUTTER" },
] as const;
